# Generated by Django 6.0.3 on 2026-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0017_remove_tabel_1a4_sks_tambahan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabel_6_misi',
            options={},
        ),
        migrations.AddField(
            model_name='tabel_6_misi',
            name='misi_ps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabel_6_misi',
            name='sasaran_ps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabel_6_misi',
            name='tujuan_ps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
