# Generated by Django 6.0.2 on 2026-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lkps_app', '0018_alter_tabel_6_misi_options_tabel_6_misi_misi_ps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanFitur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_fitur', models.CharField(choices=[('kriteria_6', 'Kriteria 6 - Visi Misi'), ('kriteria_5', 'Kriteria 5 - Tata Kelola')], max_length=50, unique=True)),
                ('nama_fitur', models.CharField(max_length=100)),
                ('grup_akses', models.ManyToManyField(blank=True, help_text='Siapa yang bisa melihat', related_name='fitur_akses', to='auth.group')),
                ('grup_edit', models.ManyToManyField(blank=True, help_text='Siapa yang bisa mengedit/mengisi', related_name='fitur_edit', to='auth.group')),
            ],
        ),
    ]
