# Generated by Django 6.0.3 on 2026-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0019_pengaturanfitur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengaturanfitur',
            options={'verbose_name': 'Pengaturan Fitur', 'verbose_name_plural': 'Pengaturan Fitur'},
        ),
        migrations.RemoveField(
            model_name='pengaturanfitur',
            name='grup_akses',
        ),
        migrations.RemoveField(
            model_name='pengaturanfitur',
            name='grup_edit',
        ),
        migrations.AddField(
            model_name='pengaturanfitur',
            name='bisa_diedit_user',
            field=models.BooleanField(default=False, help_text='Jika ON, semua user (non-staff) bisa mengisi/mengedit data.'),
        ),
        migrations.AddField(
            model_name='pengaturanfitur',
            name='bisa_dilihat_user',
            field=models.BooleanField(default=True, help_text='Jika OFF, halaman dikunci dan tidak bisa diakses oleh non-staff.'),
        ),
    ]
