# Generated by Django 6.0.3 on 2026-05-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0020_refactor_pengaturan_fitur_to_boolean_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanfitur',
            name='tampilkan_pengaturan_ke_user',
            field=models.BooleanField(default=False, help_text='Jika OFF, kolom/panel Pengaturan Akses akan disembunyikan dari user biasa.'),
        ),
    ]
