# Generated by Django 6.0.3 on 2026-05-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0021_add_tampilkan_pengaturan_ke_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturanfitur',
            name='kode_fitur',
            field=models.CharField(choices=[('kriteria_1', 'Kriteria 1 - Visi, Misi, Tujuan, dan Strategi'), ('kriteria_2', 'Kriteria 2 - Tata Pamong, Tata Kelola, dan Kerjasama'), ('kriteria_3', 'Kriteria 3 - Mahasiswa'), ('kriteria_4', 'Kriteria 4 - Sumber Daya Manusia'), ('kriteria_5', 'Kriteria 5 - Keuangan, Sarana, dan Prasarana'), ('kriteria_6', 'Kriteria 6 - Pendidikan'), ('kriteria_7', 'Kriteria 7 - Penelitian'), ('kriteria_8', 'Kriteria 8 - Pengabdian kepada Masyarakat'), ('kriteria_9', 'Kriteria 9 - Luaran dan Capaian Tridharma')], max_length=50, unique=True),
        ),
    ]
