# Generated by Django 6.0.2 on 2026-05-23 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkps_app', '0022_update_kode_fitur_choices_9_kriteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AksesKriteriaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akses_kriteria_1', models.BooleanField(default=False)),
                ('akses_kriteria_2', models.BooleanField(default=False)),
                ('akses_kriteria_3', models.BooleanField(default=False)),
                ('akses_kriteria_4', models.BooleanField(default=False)),
                ('akses_kriteria_5', models.BooleanField(default=False)),
                ('akses_kriteria_6', models.BooleanField(default=False)),
                ('akses_kriteria_7', models.BooleanField(default=False)),
                ('akses_kriteria_8', models.BooleanField(default=False)),
                ('akses_kriteria_9', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='akses_kriteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Akses Kriteria User',
                'verbose_name_plural': 'Akses Kriteria User',
            },
        ),
    ]
